global:
  domain: argocd.imyashkale.com
  image:
    tag: "v2.6.6"
server:
  extraArgs:
    - --insecure
  ingress:
    hostname: "argocd.imyashkale.com"
    enabled: true
    controller: aws
    ingressClassName: aws-ingress-class
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/group.name: ultra
      alb.ingress.kubernetes.io/group.order: 15
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: 15
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: 5
      alb.ingress.kubernetes.io/success-codes: 200
      alb.ingress.kubernetes.io/healthy-threshold-count: 2
      alb.ingress.kubernetes.io/unhealthy-threshold-count: 2
      alb.ingress.kubernetes.io/healthcheck-port: "80"
      external-dns.alpha.kubernetes.io/hostname: "argocd.imyashkale.com"
    aws:
      serviceType: ClusterIP
      backendProtocolVersion: GRPC
